name: Remove Member From Team
description: Removes a GitHub user from a specified team in an organization using the GitHub API.
author: Louisiana Office of Technology Services

inputs:
  member-name:
    description: 'The slugified username of the member to be removed (e.g., "john-doe")'
    required: true
  team-name:
    description: 'The slugified name of the team (e.g., "code-approvers")'
    required: true
  token:
    description: 'GitHub token with organization admin permissions'
    required: true
  owner:
    description: 'The owner of the organization (user or organization)'
    required: true

outputs:
  result:
    description: 'Result of the remove member operation ("success" or "failure")'
    value: ${{ steps.action.outputs.result }}
  error-message:
    description: 'Error message if the remove member operation fails'
    value: ${{ steps.action.outputs.error-message }}

runs:
  using: composite
  steps:
    - name: Remove Member from Team
      id: action
      run: |
        source ${{ github.action_path }}/action.sh
        remove_member_from_team "${{ inputs.member-name }}" "${{ inputs.team-name }}" "${{ inputs.token }}" "${{ inputs.owner }}"
      shell: bash
